In [1]:
import pandas as pd
import numpy as np

In [2]:
#Read the movie Dataset
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [3]:
items.head(3)

movie id        movie title release date  video release date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   

                                            IMDb URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1           1  ...        0          0       0        0   
1          1          0           0  ...        0          0       0        0   
2          0          0           0  ...        0          0       0        0   

   Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0       0         0    0        0  
1        0        0       0         1    0        0  
2        0        0       0         1    0        0  

[3 rows x 24 columns]

In [4]:
# Select only needed Item
movie_content=items[['movie id','movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

In [5]:
movie_content

movie id                                movie title  Action  Adventure  \
0            1                           Toy Story (1995)       0          0   
1            2                           GoldenEye (1995)       1          1   
2            3                          Four Rooms (1995)       0          0   
3            4                          Get Shorty (1995)       1          0   
4            5                             Copycat (1995)       0          0   
...        ...                                        ...     ...        ...   
1677      1678                          Mat' i syn (1997)       0          0   
1678      1679                           B. Monkey (1998)       0          0   
1679      1680                       Sliding Doors (1998)       0          0   
1680      1681                        You So Crazy (1994)       0          0   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)       0          0   

      Animation  Children's  Comedy  Crime  Documentary  Drama  Fantasy  \
0             1           1       1      0            0      0        0   
1             0           0       0      0            0      0        0   
2             0           0       0      0            0      0        0   
3             0           0       1      0            0      1        0   
4             0           0       0      1            0      1        0   
...         ...         ...     ...    ...          ...    ...      ...   
1677          0           0       0      0            0      1        0   
1678          0           0       0      0            0      0        0   
1679          0           0       0      0            0      1        0   
1680          0           0       1      0            0      0        0   
1681          0           0       0      0            0      1        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 20 columns]

In [6]:
#read the ratings dataset
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

In [7]:
ratings

user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [8]:
ratings[ratings['user_id']==196][['movie_id','rating']]

movie_id  rating
0           242       3
940         393       4
1133        381       4
1812        251       3
1896        655       5
2374         67       5
6910        306       4
7517        238       4
7842        663       5
10017       111       4
10254       580       2
10981        25       4
13733       286       5
14606        94       3
16834       692       5
17102         8       5
17830       428       4
18853      1118       4
21605        70       3
22271        66       3
22773       257       2
23189       108       4
24030       202       3
25726       340       3
32721       287       3
33536       116       3
35197       382       4
36281       285       5
41539      1241       3
42384      1007       4
50147       411       4
52726       153       5
56628        13       2
59165       762       3
59607       173       2
60199      1022       4
60706       845       4
78787       269       3
87863       110       1

In [9]:
# Create Pivot Table  which will act as user vector
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [10]:
data_matrix=datama.replace(np.nan,0)

In [11]:
data_matrix

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940        0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941        5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943        0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [12]:
# User Vectors
#all the user_id will be in the place of columns
user_vector=data_matrix.T

In [13]:
user_vector

user_id   1    2    3    4    5    6    7    8    9    10   ...  934  935  \
movie_id                                                    ...             
1         5.0  4.0  0.0  0.0  4.0  4.0  0.0  0.0  0.0  4.0  ...  2.0  3.0   
2         3.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  ...  4.0  0.0   
3         4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4         3.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  ...  5.0  0.0   
5         3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1678      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1679      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1680      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1681      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1682      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

user_id   936  937  938  939  940  941  942  943  
movie_id                                          
1         4.0  0.0  4.0  0.0  0.0  5.0  0.0  0.0  
2         0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
3         4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4         0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  
5         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  ...  
1678      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1679      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1680      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1681      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1682      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1682 rows x 943 columns]

In [14]:
# Create movie Vector
movie_vec=items[['Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

In [15]:
movie_vec

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          1          1          0           0       0      0            0   
2          0          0          0           0       0      0            0   
3          1          0          0           0       1      0            0   
4          0          0          0           0       0      1            0   
...      ...        ...        ...         ...     ...    ...          ...   
1677       0          0          0           0       0      0            0   
1678       0          0          0           0       0      0            0   
1679       0          0          0           0       0      0            0   
1680       0          0          0           0       1      0            0   
1681       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        0          0       0        0        0        0       0   
2         0        0          0       0        0        0        0       0   
3         1        0          0       0        0        0        0       0   
4         1        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
1677      1        0          0       0        0        0        0       0   
1678      0        0          0       0        0        0        1       0   
1679      1        0          0       0        0        0        1       0   
1680      0        0          0       0        0        0        0       0   
1681      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            1    0        0  
2            1    0        0  
3            0    0        0  
4            1    0        0  
...        ...  ...      ...  
1677         0    0        0  
1678         1    0        0  
1679         0    0        0  
1680         0    0        0  
1681         0    0        0  

[1682 rows x 18 columns]

In [16]:
# Rename the index
movie_vec.index=range(1,1683)

In [17]:
movie_vector=movie_vec.T

In [18]:
##this table contains movie with different categories
movie_vector

1     2     3     4     5     6     7     8     9     10    ...  \
Action          0     1     0     1     0     0     0     0     0     0  ...   
Adventure       0     1     0     0     0     0     0     0     0     0  ...   
Animation       1     0     0     0     0     0     0     0     0     0  ...   
Children's      1     0     0     0     0     0     0     1     0     0  ...   
Comedy          1     0     0     1     0     0     0     1     0     0  ...   
Crime           0     0     0     0     1     0     0     0     0     0  ...   
Documentary     0     0     0     0     0     0     0     0     0     0  ...   
Drama           0     0     0     1     1     1     1     1     1     1  ...   
Fantasy         0     0     0     0     0     0     0     0     0     0  ...   
Film-Noir       0     0     0     0     0     0     0     0     0     0  ...   
Horror          0     0     0     0     0     0     0     0     0     0  ...   
Musical         0     0     0     0     0     0     0     0     0     0  ...   
Mystery         0     0     0     0     0     0     0     0     0     0  ...   
Romance         0     0     0     0     0     0     0     0     0     0  ...   
Sci-Fi          0     0     0     0     0     0     1     0     0     0  ...   
Thriller        0     1     1     0     1     0     0     0     0     0  ...   
War             0     0     0     0     0     0     0     0     0     1  ...   
Western         0     0     0     0     0     0     0     0     0     0  ...   

             1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
Action          1     0     0     0     0     0     0     0     0     0  
Adventure       0     0     0     0     0     0     0     0     0     0  
Animation       0     0     0     0     0     0     0     0     0     0  
Children's      0     0     0     0     0     0     0     0     0     0  
Comedy          0     0     0     0     0     0     0     0     1     0  
Crime           0     0     0     0     0     0     0     0     0     0  
Documentary     0     0     0     0     0     0     0     0     0     0  
Drama           0     1     1     1     1     1     0     1     0     1  
Fantasy         0     0     0     0     0     0     0     0     0     0  
Film-Noir       0     0     0     0     0     0     0     0     0     0  
Horror          0     0     0     0     0     0     0     0     0     0  
Musical         0     0     0     0     0     0     0     0     0     0  
Mystery         0     0     0     0     0     0     0     0     0     0  
Romance         0     0     0     0     0     0     1     1     0     0  
Sci-Fi          0     0     0     0     0     0     0     0     0     0  
Thriller        1     0     0     0     0     0     1     0     0     0  
War             0     0     0     0     0     0     0     0     0     0  
Western         0     0     0     0     0     0     0     0     0     0  

[18 rows x 1682 columns]

# Create the content vector(user_vector and Item Vector)

In [19]:
#check for user1
u1=ratings[ratings['user_id']==1][['movie_id','rating']]

In [20]:
#user1 seen movies and its rating
u1

movie_id  rating
202          61       4
305         189       3
333          33       4
334         160       4
478          20       4
...         ...     ...
92049        28       4
92487       172       5
94019       122       3
96699       152       5
99073        94       2

[272 rows x 2 columns]

In [21]:
#to get the category_wise movies seen by user1 , create an empty list
u1_list=[]
for i in u1['movie_id']:
    f=movie_vector[i].values
    u1_list.append(f)

In [22]:
u1_list

[array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64),

In [23]:
#to get the category_wise movies seen by the u1 in a tabular format
table_u1=pd.DataFrame(u1_list,columns=range(1,19))

In [24]:
table_u1

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
1     0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   1   0   0   0   0   0   1   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
267   1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0
268   1   1   0   0   0   0   0   1   0   0   0   0   0   1   1   0   1   0
269   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
270   0   0   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[272 rows x 18 columns]

In [25]:
#create a single vector for each user by summing up the columns
vec=[]
for j in range(1,19):
    sum_u1=sum(table_u1[j])
    vec.append(sum_u1/272)

In [26]:
#these were the overall categorical values for the user1 seen movies
vec

[0.2757352941176471,
 0.15441176470588236,
 0.04411764705882353,
 0.09191176470588236,
 0.33455882352941174,
 0.09191176470588236,
 0.01838235294117647,
 0.39338235294117646,
 0.007352941176470588,
 0.003676470588235294,
 0.04779411764705882,
 0.04779411764705882,
 0.01838235294117647,
 0.16176470588235295,
 0.15808823529411764,
 0.19117647058823528,
 0.09191176470588236,
 0.022058823529411766]

In [27]:
# function to create a sinle vector for all users seen movies
def user_vector(ratings,movie_vector):
    vector=[]
    for user in range(1,944): # Each user id to create vector
        u1=ratings[ratings['user_id']==user][['movie_id','rating']]  
        u1_list=[]
        for i in u1['movie_id']: # Each user watched movie genre vector
            f=movie_vector[i].values
            u1_list.append(f)
        table_u1=pd.DataFrame(u1_list,columns=range(1,19))
        vec=[]
        for j in range(1,19): # Sum up the each genre of the user
            g=sum(table_u1[j])
            vec.append(g/len(u1))
        vector.append(vec)
    return vector

In [28]:
vector=user_vector(ratings,movie_vector)

In [29]:
# converting into Dataset
users_vector=pd.DataFrame(vector)

In [30]:
users_vector

0         1         2         3         4         5         6   \
0    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
1    0.161290  0.048387  0.016129  0.064516  0.258065  0.145161  0.000000   
2    0.259259  0.074074  0.000000  0.000000  0.222222  0.185185  0.018519   
3    0.333333  0.166667  0.000000  0.000000  0.166667  0.166667  0.041667   
4    0.320000  0.188571  0.080000  0.165714  0.468571  0.051429  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
938  0.367347  0.204082  0.020408  0.020408  0.306122  0.061224  0.000000   
939  0.214953  0.112150  0.018692  0.046729  0.392523  0.065421  0.000000   
940  0.454545  0.318182  0.136364  0.090909  0.318182  0.045455  0.000000   
941  0.227848  0.139241  0.050633  0.164557  0.278481  0.000000  0.000000   
942  0.380952  0.208333  0.011905  0.053571  0.333333  0.107143  0.000000   

           7         8         9         10        11        12        13  \
0    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
1    0.564516  0.016129  0.032258  0.032258  0.016129  0.064516  0.258065   
2    0.407407  0.000000  0.037037  0.092593  0.037037  0.203704  0.092593   
3    0.250000  0.000000  0.000000  0.041667  0.041667  0.208333  0.125000   
4    0.154286  0.011429  0.005714  0.160000  0.068571  0.017143  0.108571   
..        ...       ...       ...       ...       ...       ...       ...   
938  0.367347  0.020408  0.000000  0.020408  0.020408  0.020408  0.204082   
939  0.448598  0.000000  0.028037  0.037383  0.065421  0.028037  0.224299   
940  0.227273  0.000000  0.000000  0.000000  0.045455  0.045455  0.045455   
941  0.392405  0.025316  0.012658  0.037975  0.063291  0.113924  0.215190   
942  0.339286  0.011905  0.000000  0.083333  0.023810  0.017857  0.196429   

           14        15        16        17  
0    0.158088  0.191176  0.091912  0.022059  
1    0.064516  0.193548  0.048387  0.000000  
2    0.148148  0.388889  0.092593  0.000000  
3    0.250000  0.458333  0.083333  0.000000  
4    0.188571  0.108571  0.080000  0.011429  
..        ...       ...       ...       ...  
938  0.163265  0.244898  0.061224  0.000000  
939  0.177570  0.186916  0.140187  0.000000  
940  0.363636  0.318182  0.045455  0.000000  
941  0.075949  0.253165  0.126582  0.037975  
942  0.130952  0.208333  0.089286  0.053571  

[943 rows x 18 columns]

In [31]:
users_vector.shape

(943, 18)

In [32]:
movie_vector.shape

(18, 1682)

In [33]:
# Dot matrix for  user_vector and movie_vetcor
content_vector=np.dot(users_vector,movie_vector)

In [34]:
content_vector=pd.DataFrame(content_vector)

In [35]:
content_vectors=content_vector.T

In [36]:
content_vector

0         1         2         3         4         5         6     \
0    0.470588  0.621324  0.191176  1.003676  0.676471  0.393382  0.551471   
1    0.338710  0.403226  0.193548  0.983871  0.903226  0.564516  0.629032   
2    0.222222  0.722222  0.388889  0.888889  0.981481  0.407407  0.555556   
3    0.166667  0.958333  0.458333  0.750000  0.875000  0.250000  0.500000   
4    0.714286  0.617143  0.108571  0.942857  0.314286  0.154286  0.342857   
..        ...       ...       ...       ...       ...       ...       ...   
938  0.346939  0.816327  0.244898  1.040816  0.673469  0.367347  0.530612   
939  0.457944  0.514019  0.186916  1.056075  0.700935  0.448598  0.626168   
940  0.545455  1.090909  0.318182  1.000000  0.590909  0.227273  0.590909   
941  0.493671  0.620253  0.253165  0.898734  0.645570  0.392405  0.468354   
942  0.398810  0.797619  0.208333  1.053571  0.654762  0.339286  0.470238   

         7         8         9     ...      1672      1673      1674  \
0    0.819853  0.393382  0.485294  ...  0.466912  0.393382  0.393382   
1    0.887097  0.564516  0.612903  ...  0.354839  0.564516  0.564516   
2    0.629630  0.407407  0.500000  ...  0.648148  0.407407  0.407407   
3    0.416667  0.250000  0.333333  ...  0.791667  0.250000  0.250000   
4    0.788571  0.154286  0.234286  ...  0.428571  0.154286  0.154286   
..        ...       ...       ...  ...       ...       ...       ...   
938  0.693878  0.367347  0.428571  ...  0.612245  0.367347  0.367347   
939  0.887850  0.448598  0.588785  ...  0.401869  0.448598  0.448598   
940  0.636364  0.227273  0.272727  ...  0.772727  0.227273  0.227273   
941  0.835443  0.392405  0.518987  ...  0.481013  0.392405  0.392405   
942  0.726190  0.339286  0.428571  ...  0.589286  0.339286  0.339286   

         1675      1676      1677      1678      1679      1680      1681  
0    0.393382  0.393382  0.393382  0.352941  0.555147  0.334559  0.393382  
1    0.564516  0.564516  0.564516  0.451613  0.822581  0.258065  0.564516  
2    0.407407  0.407407  0.407407  0.481481  0.500000  0.222222  0.407407  
3    0.250000  0.250000  0.250000  0.583333  0.375000  0.166667  0.250000  
4    0.154286  0.154286  0.154286  0.217143  0.262857  0.468571  0.154286  
..        ...       ...       ...       ...       ...       ...       ...  
938  0.367347  0.367347  0.367347  0.448980  0.571429  0.306122  0.367347  
939  0.448598  0.448598  0.448598  0.411215  0.672897  0.392523  0.448598  
940  0.227273  0.227273  0.227273  0.363636  0.272727  0.318182  0.227273  
941  0.392405  0.392405  0.392405  0.468354  0.607595  0.278481  0.392405  
942  0.339286  0.339286  0.339286  0.404762  0.535714  0.333333  0.339286  

[943 rows x 1682 columns]

In [37]:
content_vector.to_csv("content_vector.csv",index=False)

# individual check for user

In [38]:
u2=ratings[ratings['user_id']==3]['movie_id'].values

In [39]:
len(u2)

54

In [40]:
val=content_vectors[content_vectors[3]>(content_vectors[3].max()-0.5)][2]

In [41]:
val

1       0.722222
16      1.148148
20      0.981481
27      1.055556
32      0.740741
          ...   
1313    0.722222
1490    1.055556
1555    1.055556
1558    1.055556
1595    0.796296
Name: 2, Length: 70, dtype: float64

In [42]:
recom=[]
for i in val.index:
    if i in u2:
        pass
    else:
        recom.append(i)
        

In [43]:
recom

[1,
 16,
 20,
 27,
 32,
 49,
 53,
 54,
 67,
 95,
 116,
 117,
 128,
 134,
 144,
 163,
 171,
 175,
 180,
 182,
 183,
 194,
 243,
 244,
 251,
 256,
 259,
 269,
 297,
 357,
 402,
 425,
 565,
 567,
 635,
 664,
 747,
 750,
 768,
 770,
 801,
 824,
 826,
 829,
 830,
 854,
 901,
 913,
 915,
 916,
 929,
 944,
 975,
 981,
 1012,
 1015,
 1024,
 1088,
 1104,
 1137,
 1138,
 1313,
 1490,
 1555,
 1558,
 1595]

In [44]:
len(recom)

66

In [45]:
def contenBased(content_vector,ratings,thres,user_id):
    u2=ratings[ratings['user_id']==user_id]['movie_id'].values
    val=content_vectors[content_vectors[user_id]>(content_vectors[user_id].max()-thres)][2]
    recom=[]
    for i in val.index:
        if i in u2:
            pass
        else:
            recom.append(i)
    return recom

In [46]:
recom=contenBased(content_vector,ratings,0.5,3)


In [47]:
recom

[1,
 16,
 20,
 27,
 32,
 49,
 53,
 54,
 67,
 95,
 116,
 117,
 128,
 134,
 144,
 163,
 171,
 175,
 180,
 182,
 183,
 194,
 243,
 244,
 251,
 256,
 259,
 269,
 297,
 357,
 402,
 425,
 565,
 567,
 635,
 664,
 747,
 750,
 768,
 770,
 801,
 824,
 826,
 829,
 830,
 854,
 901,
 913,
 915,
 916,
 929,
 944,
 975,
 981,
 1012,
 1015,
 1024,
 1088,
 1104,
 1137,
 1138,
 1313,
 1490,
 1555,
 1558,
 1595]